/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    members: Member;
    articles: Article;
    'news-stories': NewsStory;
    businesses: Business;
    'business-submissions': BusinessSubmission;
    embassies: Embassy;
    events: Event;
    'learning-paths': LearningPath;
    'learning-resources': LearningResource;
    media: Media;
    'practice-groups': PracticeGroup;
    'yki-resources': YkiResource;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'news-stories': NewsStoriesSelect<false> | NewsStoriesSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    'business-submissions': BusinessSubmissionsSelect<false> | BusinessSubmissionsSelect<true>;
    embassies: EmbassiesSelect<false> | EmbassiesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'learning-paths': LearningPathsSelect<false> | LearningPathsSelect<true>;
    'learning-resources': LearningResourcesSelect<false> | LearningResourcesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'practice-groups': PracticeGroupsSelect<false> | PracticeGroupsSelect<true>;
    'yki-resources': YkiResourcesSelect<false> | YkiResourcesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Super admins manage users and members. Editors manage published site content.
   */
  role: 'super-admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  provider: 'password' | 'google' | 'both';
  googleSubject?: string | null;
  picture?: string | null;
  /**
   * Optional city or municipality in Finland.
   */
  city?: string | null;
  /**
   * Languages the member would like to use on Expats.fi.
   */
  languages?: string | null;
  /**
   * Optional stage of the move to Finland.
   */
  arrivalStage?: ('planning' | 'new-arrival' | 'settling-in' | 'established') | null;
  /**
   * Topics selected by the member for future recommendations.
   */
  interests?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Occasional emails about useful new guides and directory updates.
   */
  emailUpdates?: boolean | null;
  /**
   * The regular Expats.fi newsletter, when available.
   */
  newsletter?: boolean | null;
  /**
   * Guides this member has saved for later.
   */
  savedArticles?: (number | Article)[] | null;
  /**
   * Businesses this member has saved for later.
   */
  savedBusinesses?: (number | Business)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  description: string;
  category:
    | 'Immigration & permits'
    | 'Work & money'
    | 'Housing'
    | 'Health & wellbeing'
    | 'Getting around'
    | 'Family'
    | 'Everyday life';
  publishedAt: string;
  readingMinutes: number;
  featured?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Original URL retained for migration provenance.
   */
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: number;
  name: string;
  slug: string;
  summary: string;
  description: string;
  categories: {
    label: string;
    id?: string | null;
  }[];
  locations: {
    label: string;
    id?: string | null;
  }[];
  address: string;
  website: string;
  newsletterUrl?: string | null;
  phone?: string | null;
  /**
   * Include the @ symbol, for example @expats.fi
   */
  instagramHandle?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  bookingUrl?: string | null;
  whatsapp?: string | null;
  currentOffer?: string | null;
  currentOfferEndsAt?: string | null;
  imagePath?: string | null;
  imageAlt?: string | null;
  logoPath?: string | null;
  logoAlt?: string | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Original Expats.fi reporting and explainers. Keep the source list and checked date current.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-stories".
 */
export interface NewsStory {
  id: number;
  title: string;
  slug: string;
  /**
   * A warm, useful summary for the News page and search results.
   */
  standfirst: string;
  category: 'Helsinki' | 'Finland' | 'Work & money' | 'Life admin' | 'Culture & community';
  publishedAt: string;
  readingMinutes: number;
  featured?: boolean | null;
  /**
   * The plain-English answer to: what does this mean for somebody living here?
   */
  practicalSummary: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * An array of source objects: [{ "name": "City of Helsinki", "url": "https://..." }].
   */
  sources:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceCheckedAt: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-submissions".
 */
export interface BusinessSubmission {
  id: number;
  submittedBy: number | Member;
  businessName: string;
  website: string;
  location: string;
  category: string;
  description: string;
  contactName: string;
  contactEmail: string;
  status: 'pending' | 'approved' | 'needs-changes' | 'declined';
  /**
   * Internal notes shown to administrators.
   */
  reviewerNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "embassies".
 */
export interface Embassy {
  id: number;
  country: string;
  countryCode: string;
  slug: string;
  region: 'Africa' | 'Asia' | 'Europe' | 'North America' | 'South America' | 'Oceania';
  representationType:
    'resident-embassy' | 'representative-office' | 'non-resident-embassy' | 'honorary-consulate' | 'foreign-ministry';
  missionName: string;
  city: string;
  hostCountry: string;
  /**
   * Official mission website, when known.
   */
  website?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Primary official directory used to verify this representation.
   */
  sourceUrl: string;
  notes?: string | null;
  lastVerifiedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  category: 'Music & nightlife' | 'Arts & culture' | 'Food & markets' | 'Community & free' | 'Sports & outdoors';
  startDate: string;
  endDate: string;
  dateLabel: string;
  timeLabel: string;
  location: string;
  address: string;
  district: string;
  /**
   * Optional map coordinates: { "latitude": 60.17, "longitude": 24.94 }.
   */
  coordinates?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  blurb: string;
  /**
   * An array of story paragraphs.
   */
  description:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  price: string;
  free?: boolean | null;
  familyFriendly?: boolean | null;
  ageNote?: string | null;
  bookingNote: string;
  sourceName: string;
  sourceUrl: string;
  /**
   * Human-readable date shown to visitors.
   */
  lastChecked: string;
  /**
   * An array of { mode, advice } route tips.
   */
  transport:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-paths".
 */
export interface LearningPath {
  id: number;
  title: string;
  level: string;
  recipe: string;
  /**
   * An array of related resource names.
   */
  links:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastReviewedAt: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-resources".
 */
export interface LearningResource {
  id: number;
  name: string;
  category: 'Free foundations' | 'Courses & teachers' | 'Apps & tools' | 'Listen & watch';
  cost: 'Free' | 'Freemium' | 'Paid' | 'Free & paid';
  level: string;
  format: string;
  url: string;
  description: string;
  bestFor: string;
  note?: string | null;
  featured?: boolean | null;
  lastReviewedAt: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-groups".
 */
export interface PracticeGroup {
  id: number;
  name: string;
  location: string;
  schedule: string;
  cost: string;
  url: string;
  description: string;
  checkFirst: string;
  lastReviewedAt: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yki-resources".
 */
export interface YkiResource {
  id: number;
  name: string;
  url: string;
  description: string;
  lastReviewedAt: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'news-stories';
        value: number | NewsStory;
      } | null)
    | ({
        relationTo: 'businesses';
        value: number | Business;
      } | null)
    | ({
        relationTo: 'business-submissions';
        value: number | BusinessSubmission;
      } | null)
    | ({
        relationTo: 'embassies';
        value: number | Embassy;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'learning-paths';
        value: number | LearningPath;
      } | null)
    | ({
        relationTo: 'learning-resources';
        value: number | LearningResource;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'practice-groups';
        value: number | PracticeGroup;
      } | null)
    | ({
        relationTo: 'yki-resources';
        value: number | YkiResource;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  googleSubject?: T;
  picture?: T;
  city?: T;
  languages?: T;
  arrivalStage?: T;
  interests?: T;
  emailUpdates?: T;
  newsletter?: T;
  savedArticles?: T;
  savedBusinesses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  publishedAt?: T;
  readingMinutes?: T;
  featured?: T;
  content?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-stories_select".
 */
export interface NewsStoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  standfirst?: T;
  category?: T;
  publishedAt?: T;
  readingMinutes?: T;
  featured?: T;
  practicalSummary?: T;
  content?: T;
  sources?: T;
  sourceCheckedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  description?: T;
  categories?:
    | T
    | {
        label?: T;
        id?: T;
      };
  locations?:
    | T
    | {
        label?: T;
        id?: T;
      };
  address?: T;
  website?: T;
  newsletterUrl?: T;
  phone?: T;
  instagramHandle?: T;
  instagram?: T;
  facebook?: T;
  youtube?: T;
  tiktok?: T;
  bookingUrl?: T;
  whatsapp?: T;
  currentOffer?: T;
  currentOfferEndsAt?: T;
  imagePath?: T;
  imageAlt?: T;
  logoPath?: T;
  logoAlt?: T;
  featured?: T;
  status?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-submissions_select".
 */
export interface BusinessSubmissionsSelect<T extends boolean = true> {
  submittedBy?: T;
  businessName?: T;
  website?: T;
  location?: T;
  category?: T;
  description?: T;
  contactName?: T;
  contactEmail?: T;
  status?: T;
  reviewerNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "embassies_select".
 */
export interface EmbassiesSelect<T extends boolean = true> {
  country?: T;
  countryCode?: T;
  slug?: T;
  region?: T;
  representationType?: T;
  missionName?: T;
  city?: T;
  hostCountry?: T;
  website?: T;
  phone?: T;
  email?: T;
  address?: T;
  sourceUrl?: T;
  notes?: T;
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  startDate?: T;
  endDate?: T;
  dateLabel?: T;
  timeLabel?: T;
  location?: T;
  address?: T;
  district?: T;
  coordinates?: T;
  blurb?: T;
  description?: T;
  price?: T;
  free?: T;
  familyFriendly?: T;
  ageNote?: T;
  bookingNote?: T;
  sourceName?: T;
  sourceUrl?: T;
  lastChecked?: T;
  transport?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-paths_select".
 */
export interface LearningPathsSelect<T extends boolean = true> {
  title?: T;
  level?: T;
  recipe?: T;
  links?: T;
  lastReviewedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-resources_select".
 */
export interface LearningResourcesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  cost?: T;
  level?: T;
  format?: T;
  url?: T;
  description?: T;
  bestFor?: T;
  note?: T;
  featured?: T;
  lastReviewedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-groups_select".
 */
export interface PracticeGroupsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  schedule?: T;
  cost?: T;
  url?: T;
  description?: T;
  checkFirst?: T;
  lastReviewedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yki-resources_select".
 */
export interface YkiResourcesSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  description?: T;
  lastReviewedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'articles';
      value: number | Article;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}